/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AichatbotRouteImport } from './routes/aichatbot'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ServiceProviderBookingsRouteImport } from './routes/service-provider/bookings'
import { Route as DashboardProviderBookingsRouteImport } from './routes/dashboard/provider-bookings'
import { Route as DashboardProviderRouteImport } from './routes/dashboard/provider'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardServicesManageRouteImport } from './routes/dashboard/services/manage'
import { Route as DashboardBusinessRegisterRouteImport } from './routes/dashboard/business/register'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AichatbotRoute = AichatbotRouteImport.update({
  id: '/aichatbot',
  path: '/aichatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ServiceProviderBookingsRoute = ServiceProviderBookingsRouteImport.update({
  id: '/service-provider/bookings',
  path: '/service-provider/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProviderBookingsRoute =
  DashboardProviderBookingsRouteImport.update({
    id: '/provider-bookings',
    path: '/provider-bookings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProviderRoute = DashboardProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesManageRoute = DashboardServicesManageRouteImport.update({
  id: '/services/manage',
  path: '/services/manage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessRegisterRoute =
  DashboardBusinessRegisterRouteImport.update({
    id: '/business/register',
    path: '/business/register',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aichatbot': typeof AichatbotRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/dashboard/provider-bookings': typeof DashboardProviderBookingsRoute
  '/service-provider/bookings': typeof ServiceProviderBookingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/business/register': typeof DashboardBusinessRegisterRoute
  '/dashboard/services/manage': typeof DashboardServicesManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aichatbot': typeof AichatbotRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/dashboard/provider-bookings': typeof DashboardProviderBookingsRoute
  '/service-provider/bookings': typeof ServiceProviderBookingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/business/register': typeof DashboardBusinessRegisterRoute
  '/dashboard/services/manage': typeof DashboardServicesManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aichatbot': typeof AichatbotRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/dashboard/provider-bookings': typeof DashboardProviderBookingsRoute
  '/service-provider/bookings': typeof ServiceProviderBookingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/business/register': typeof DashboardBusinessRegisterRoute
  '/dashboard/services/manage': typeof DashboardServicesManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aichatbot'
    | '/contact'
    | '/dashboard'
    | '/fleet'
    | '/login'
    | '/register'
    | '/services'
    | '/dashboard/bookings'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/provider'
    | '/dashboard/provider-bookings'
    | '/service-provider/bookings'
    | '/dashboard/'
    | '/dashboard/business/register'
    | '/dashboard/services/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aichatbot'
    | '/contact'
    | '/fleet'
    | '/login'
    | '/register'
    | '/services'
    | '/dashboard/bookings'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/provider'
    | '/dashboard/provider-bookings'
    | '/service-provider/bookings'
    | '/dashboard'
    | '/dashboard/business/register'
    | '/dashboard/services/manage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aichatbot'
    | '/contact'
    | '/dashboard'
    | '/fleet'
    | '/login'
    | '/register'
    | '/services'
    | '/dashboard/bookings'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/provider'
    | '/dashboard/provider-bookings'
    | '/service-provider/bookings'
    | '/dashboard/'
    | '/dashboard/business/register'
    | '/dashboard/services/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AichatbotRoute: typeof AichatbotRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FleetRoute: typeof FleetRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  ServiceProviderBookingsRoute: typeof ServiceProviderBookingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aichatbot': {
      id: '/aichatbot'
      path: '/aichatbot'
      fullPath: '/aichatbot'
      preLoaderRoute: typeof AichatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/service-provider/bookings': {
      id: '/service-provider/bookings'
      path: '/service-provider/bookings'
      fullPath: '/service-provider/bookings'
      preLoaderRoute: typeof ServiceProviderBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider-bookings': {
      id: '/dashboard/provider-bookings'
      path: '/provider-bookings'
      fullPath: '/dashboard/provider-bookings'
      preLoaderRoute: typeof DashboardProviderBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/provider': {
      id: '/dashboard/provider'
      path: '/provider'
      fullPath: '/dashboard/provider'
      preLoaderRoute: typeof DashboardProviderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/manage': {
      id: '/dashboard/services/manage'
      path: '/services/manage'
      fullPath: '/dashboard/services/manage'
      preLoaderRoute: typeof DashboardServicesManageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business/register': {
      id: '/dashboard/business/register'
      path: '/business/register'
      fullPath: '/dashboard/business/register'
      preLoaderRoute: typeof DashboardBusinessRegisterRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProviderRoute: typeof DashboardProviderRoute
  DashboardProviderBookingsRoute: typeof DashboardProviderBookingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBusinessRegisterRoute: typeof DashboardBusinessRegisterRoute
  DashboardServicesManageRoute: typeof DashboardServicesManageRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProviderRoute: DashboardProviderRoute,
  DashboardProviderBookingsRoute: DashboardProviderBookingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBusinessRegisterRoute: DashboardBusinessRegisterRoute,
  DashboardServicesManageRoute: DashboardServicesManageRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AichatbotRoute: AichatbotRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FleetRoute: FleetRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  ServiceProviderBookingsRoute: ServiceProviderBookingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
